export const GET_USER_DATA = "GET_USER_DATA"; 
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const MODEL_OPEN = "MODEL_OPEN";
export const MODEL_EDIT = "MODEL_EDIT";
export const DATA_ERROR = "DATA_ERROR";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const DELETE_USER_DATA = "DELETE_USER_DATA";
export const GET_OLD_USER_DATA = "GET_OLD_USER_DATA"